services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: viator_db
      POSTGRES_USER: viator_user
      POSTGRES_PASSWORD: viator_password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://viator_user:viator_password@postgres:5432/viator_db?schema=public"
    depends_on:
      - postgres